apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: openshiftapiserveroperatorconfigs.openshiftapiserver.operator.openshift.io
  spec:
    scope: Cluster
    group: openshiftapiserver.operator.openshift.io
    version: v1alpha1
    names:
      kind: OpenShiftAPIServerOperatorConfig
      plural: openshiftapiserveroperatorconfigs
      singular: openshiftapiserveroperatorconfig
      categories:
      - coreoperators
    subresources:
      status: {}