apiVersion: operator.openshift.io/v1
kind: OpenShiftAPIServer
metadata:
  name: cluster
spec:
  managementState: Managed
  imagePullSpec: openshift/origin-hypershift:latest
  version: 3.11.0
  logging:
    level: 4
  replicas: 2
